# Generated by Django 3.2.4 on 2021-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comentarios',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
